declare const __PROD: boolean

const CORE_INPUT_KEY_STATUS_TEXT_IDLE = 'IDLE'
const CORE_INPUT_KEY_STATUS_TEXT_HELD = 'HELD'
const CORE_INPUT_KEY_STATUS_TEXT_PRESSED = 'PRESSED'
const CORE_INPUT_KEY_STATUS_TEXT_RELEASED = 'RELEASED'
