const G_CORE_MATH_TWO_PI = 2 * Math.PI
const G_CORE_MATH_DEG_TO_RAD = Math.PI / 180
const G_CORE_MATH_RAD_TO_DEG = 180 / Math.PI

const G_CORE_INPUT_DEFAULT_MOVING_TIMEOUT = 100
const G_CORE_INPUT_MOUSE_AMOUNT = 10
const G_CORE_INPUT_TOUCH_AMOUNT = 20

const G_CORE_TIME_BASE_FPS = 60

const G_CORE_FONT_DEFAULT_FAMILY = 'Nunito Sans'

const G_CORE_GAME_OBJECT_ALARM_DEACTIVATE_NUMBER = -1

const G_DEBUG_INDEX_AMOUNT = 4
const G_DEBUG_KEYCODE = 'Semicolon'
