loader.load_image(new CoreVec2(0.5, 0.5), 'loading_cover', 'assets/images/loading_cover.png')
loader.load_image(new CoreVec2(0.5, 0.5), 'menu_background', 'assets/images/menu_background.png')
loader.load_image(new CoreVec2(0.5, 0.5), 'fence', 'assets/images/fence.png')
loader.load_image(new CoreVec2(0.5, 1), 'capy', 'assets/images/capy.png')
loader.load_image(new CoreVec2(0.5, 0.86), 'grass', 'assets/images/grass.png')

loader.load_strip(new CoreVec2(0.5, 1), 'capy_idle', 'assets/images/capy_idle.png', 1, 1)
loader.load_strip(new CoreVec2(0.5, 1), 'capy_walking', 'assets/images/capy_walking.png', 4, 4)
loader.load_strip(new CoreVec2(0.5, 1), 'capy_eating', 'assets/images/capy_eating.png', 4, 4)
loader.load_strip(new CoreVec2(0.5, 0.2), 'capy_picked', 'assets/images/capy_picked.png', 4, 4)
